name: ose-course-data-science

channels:
- defaults
- conda-forge
- opensourceeconomics

dependencies:
- python=3
- numpy
- pandas
- matplotlib
- sphinx
- flake8
- pytest
- pygraphviz
- pytest-black
- pytest-flake8
- scipy
- jupyterlab
- xlrd
- jupyter
- ipython
- pip
- nbsphinx
- chaospy
- respy
- pip:
  - black==20.8b0
  - seaborn
  - statsmodels
  - linearmodels
  - black-nb
  - flake8-nb
  - kernreg
  - grmpy
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - nb_black
