name: ose-course-data-science

channels:
- defaults
- conda-forge
- opensourceeconomics

dependencies:
- numpy
- pandas
- sphinx
- flake8
- pytest
- pygraphviz
- pytest-black
- pytest-flake8
- scipy
- jupyterlab
- matplotlib
- xlrd
- seaborn
- jupyter
- ipython
- pip
- nbsphinx
- nb_black
- chaospy
- respy
- pip:
  - linearmodels
  - black-nb
  - flake8-nb
  - grmpy
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
